# ワークフロー名を定義
name: flutter-ci

# トリガーを定義
on:
  # プルリクエスト作成がトリガーとなる（GitHib Actionsが実行される）
  pull_request:
    # プルリクエスト作成時とプルリクエストを対象にコミットが行われた時
    types: [opened, synchronize]
    # 対象ブランチを指定（masterブランチに対するプルリクエストが対象）
    branches:
      - main
  
  # GitHubページ上から手動で実行できる
  workflow_dispatch:

# 実行するジョブを定義
jobs:
  checkout:
    # ジョブを実行する仮想ホストマシンタイプ
    runs-on: ubuntu-latest

    # steps配下に実行したいアクションを定義する
    steps:
      # 当該リポジトリをチェックアウト
      - name: checkout
        uses: actions/checkout@v2

  flutter_cache:
    runs-on: ubuntu-latest
    needs: checkout

    steps:
      # Flutterをインストール（キャッシュする）
      - name: flutter cache
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: "stable"
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

  install_flutter:
    runs-on: ubuntu-latest
    needs: flutter_cache

    steps:
      - name: install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.5"
          channel: "stable"

  flutter_pub_get:
    runs-on: ubuntu-latest
    needs: install_flutter

    steps:
      - name: Set up Flutter
        run: echo "${{ runner.tool_cache }}/flutter/bin" >> $GITHUB_PATH

      # Flutter pub get 実行
      - name: flutter pub get
        run: flutter pub get

  create_env:
    runs-on: ubuntu-latest
    needs: flutter_pub_get

    steps:
      # pubspec.ymlのassetsで指定している.envはGit管理していないのでCI上で別途作成する
      - name: create .env
        run: |
          touch .env
          echo QIITA_ACCESS_TOKEN=${{secrets.QIITA_ACCESS_TOKEN}} >> .env

  flutter_analyze:
    runs-on: ubuntu-latest
    needs: create_env

    steps:
      # 性的解析実行
      - name: flutter analyze
        run: flutter analyze

  flutter_test:
    runs-on: ubuntu-latest
    needs: flutter_analyze

    steps:
      # テスト実行
      - name: flutter test
        run: flutter test
