# ワークフロー名を定義
name: flutter-ci

# トリガーを定義
on:
  # プルリクエスト作成がトリガーとなる（GitHib Actionsが実行される）
  pull_request:
    # プルリクエスト作成時とプルリクエストを対象にコミットが行われた時
    types: [opened, synchronize]
    # 対象ブランチを指定（masterブランチに対するプルリクエストが対象）
    branches:
      - main
  
  # GitHubページ上から手動で実行できる
  workflow_dispatch:

# 実行するジョブを定義
jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          cache: true

      - name: Run flutter version
        run: flutter --version

      - name: Run flutter pub get
        run: flutter pub get

      - name: Install matcher
        run: echo "::add-matcher::.github/analyzer-problem-matcher.json"

      - name: Run flutter analyze
        shell: bash
        run: |
          flutter analyze | tee ./flutter_analyze_report.txt

      - name: Remove matcher
        if: always()
        run: echo "::remove-matcher owner=dart-analyzer::"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Danger
        uses: MeilCli/danger-action@1996610a4c089e3a79bf3131a70c3c1b311e32f9
        if: always()
        with:
          plugins_file: 'Gemfile'
          install_path: 'vendor/bundle'
          danger_file: 'Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.5'
          channel: 'stable'
          cache: true

      - name: Run flutter version
        run: flutter --version

      - name: Run flutter pub get
        run: flutter pub get

      - name: Run flutter test
        run: flutter test